version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: ekimo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ekimo"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: . 
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://admin:admin@db:5432/ekimo
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data: