"""Add field to product

Revision ID: 16a0e153232a
Revises: b8fa20479af1
Create Date: 2025-07-09 01:28:30.304247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a0e153232a'
down_revision: Union[str, Sequence[str], None] = 'b8fa20479af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
