"""Change barcode to BigInteger

Revision ID: 81091c43fb01
Revises: 16a0e153232a
Create Date: 2025-07-09 08:09:07.939087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81091c43fb01'
down_revision: Union[str, Sequence[str], None] = '16a0e153232a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'barcode',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint(None, 'products', ['barcode'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.alter_column('products', 'barcode',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
